# Generated by Django 2.1.4 on 2019-01-09 10:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('agra', django.db.models.manager.Manager()),
            ],
        ),
    ]
