# Generated by Django 2.1.5 on 2019-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190419_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translated_post',
            field=models.CharField(default='', max_length=500),
        ),
    ]
